# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0005_auto_20161123_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeasSources',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=50)),
                ('SourceID', models.ForeignKey(db_column='SourceID', on_delete=django.db.models.deletion.CASCADE, to='teas.Sources')),
                ('TeaID', models.ForeignKey(db_column='TeaID', on_delete=django.db.models.deletion.CASCADE, to='teas.Teas')),
            ],
            options={
                'db_table': 'TeasSources',
            },
        ),
    ]
