# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0007_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text',
        ),
    ]
