# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0012_remove_test_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teas',
            name='Description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='ProductID',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
