# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0013_auto_20161123_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='teassources',
            name='URL',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
