# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0015_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teas',
            name='TeaTypeID',
        ),
        migrations.RemoveField(
            model_name='teassources',
            name='SourceID',
        ),
        migrations.RemoveField(
            model_name='teassources',
            name='TeaID',
        ),
        migrations.DeleteModel(
            name='Sources',
        ),
        migrations.DeleteModel(
            name='Teas',
        ),
        migrations.DeleteModel(
            name='TeasSources',
        ),
        migrations.DeleteModel(
            name='TeaTypes',
        ),
    ]
