# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teas', '0016_auto_20161123_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SourceName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('LastUpdatedDate', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Teas',
            },
        ),
        migrations.CreateModel(
            name='TeasSources',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=50)),
                ('CostOz', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=1000)),
                ('IsAvailable', models.CharField(max_length=1)),
                ('LastUpdatedDate', models.CharField(max_length=25)),
                ('SourceID', models.ForeignKey(db_column='SourceID', on_delete=django.db.models.deletion.CASCADE, to='teas.Sources')),
                ('TeaID', models.ForeignKey(db_column='TeaID', on_delete=django.db.models.deletion.CASCADE, to='teas.Teas')),
            ],
            options={
                'db_table': 'TeasSources',
            },
        ),
        migrations.CreateModel(
            name='TeaTypes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TeaType', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'TeaTypes',
            },
        ),
        migrations.AddField(
            model_name='teas',
            name='TeaTypeID',
            field=models.ForeignKey(db_column='TeaTypeID', on_delete=django.db.models.deletion.CASCADE, to='teas.TeaTypes'),
        ),
    ]
