# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0017_auto_20161123_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeasSourcesView',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('TeaName', models.CharField(max_length=100)),
                ('TeaDescription', models.CharField(max_length=1000)),
                ('TeaType', models.CharField(max_length=25)),
                ('SourceName', models.CharField(max_length=25)),
                ('URL', models.CharField(max_length=1000)),
                ('CostOz', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TeasSourcesView',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='sources',
            name='URL',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
