# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0018_auto_20161128_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='teassources',
            name='AltImageURL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teassources',
            name='ImageURL',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
