# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0019_auto_20161128_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teassources',
            name='AltImageURL',
        ),
    ]
