# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0020_remove_teassources_altimageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
    ]
