# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0021_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeasTags',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TagID', models.ForeignKey(db_column='TagID', on_delete=django.db.models.deletion.CASCADE, to='teas.Tags')),
                ('TeaID', models.ForeignKey(db_column='TeaID', on_delete=django.db.models.deletion.CASCADE, to='teas.Teas')),
            ],
            options={
                'db_table': 'TeasTags',
            },
        ),
    ]
